[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


aaa

[[redirects]]
  from = "/"
    to = "https://nftticketpass.com/"
    status = 301
    force = true